sudo: required

language: python

python:
  - "2.7"

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

cache:
  directories:
    - $HOME/docker

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

install:
  - pip install coveralls
  #- pip install python-coveralls

services:
  - docker

script:
  - package/test/runAllTests.sh

after_success:
  - sudo cp . /app -R
  #- sudo cd /app/package/test/
  - coveralls debug